// <auto-generated />
using GuardRelay;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuardRelay.Migrations
{
    [DbContext(typeof(GuardRelayContext))]
    [Migration("20240105160229_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("GuardRelay.PowerSnapshot", b =>
                {
                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EnergyLine1")
                        .HasColumnType("REAL");

                    b.Property<double>("EnergyLine2")
                        .HasColumnType("REAL");

                    b.Property<double>("EnergyLine3")
                        .HasColumnType("REAL");

                    b.Property<double>("PowerLine1")
                        .HasColumnType("REAL");

                    b.Property<double>("PowerLine2")
                        .HasColumnType("REAL");

                    b.Property<double>("PowerLine3")
                        .HasColumnType("REAL");

                    b.HasKey("Timestamp");

                    b.ToTable("PowerSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
